### ISSUE TITLE
Type hint -induced Error at module import on Python<=3.8

### ISSUE THREAD

**Issue by deanziyangyu** [ssklykov/zernpy#4]
Hello,

## Problem

I am trying to import zernpy with Python 3.8.5 on Windows 10. It immediately throws the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\zernpy\__init__.py", line 20, in <module>
    from .zernpsf import ZernPSF  # class for ZernPSF auto export on the import call of the package
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\zernpy\zernpsf.py", line 26, in <module>
    from .utils.intmproc import DispenserManager
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\zernpy\utils\intmproc.py", line 295, in <module>
    def test_plus(x: float | int) -> float | int:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

On another linux computer with python 3.10.12 importing the module runs without error.

I think this is because the `|`operator for typehint was only introduced in python 3.9, but the program should benefit from being able to run on other platforms where it is not convienient to upgrade the python version, and also since it depends on very few packages already (numpy, matplotlib, scipy).

## Potential Solution

- Adding `from __future__ import annotations` on the files with the Python==3.9 -style type hint, from [https://stackoverflow.com/a/63939319](url)
- Or PEP484-like type hint by importing typing [https://peps.python.org/pep-0484/](url)

Thanks in advance,
Dean

**Comment by sklykov** [comment]
Hello Dean, 

Thanks for spotting the bug and using the library!
I've made today the new version of the library, there this bug should be fixed. You may update the package version and try again the import in your Python 3.8.5 environment.

**Comment by deanziyangyu** [comment]
Seems to import properly now. Thanks!
